### ISSUE TITLE
発生するワーニングの抑制

### ISSUE THREAD

**Issue by HyodaKazuaki** [nomunomu0504/covid19#100]
## 改善詳細 / Details of Improvement
- 本番/開発環境でページを表示すると、ワーニングが発生する
    - moment.jsのものだが現在はまったく使っていないため、無効化できるのではないか

## ログ / Log
```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 2/17 ~ 2/23, _f: undefined, _strict: undefined, _locale: [object Object]
Error
    at Function.eval [as createFromInputFallback] (webpack-internal:///./node_modules/moment/moment.js:319:98)
    at configFromString (webpack-internal:///./node_modules/moment/moment.js:2384:15)
    at configFromInput (webpack-internal:///./node_modules/moment/moment.js:2610:13)
    at prepareConfig (webpack-internal:///./node_modules/moment/moment.js:2593:13)
    at createFromConfig (webpack-internal:///./node_modules/moment/moment.js:2560:44)
    at createLocalOrUTC (webpack-internal:///./node_modules/moment/moment.js:2647:16)
    at createLocal (webpack-internal:///./node_modules/moment/moment.js:2651:16)
    at hooks (webpack-internal:///./node_modules/moment/moment.js:11:29)
    at DateAdapter.parse (webpack-internal:///./node_modules/chart.js/dist/Chart.js:14711:12)
    at toTimestamp (webpack-internal:///./node_modules/chart.js/dist/Chart.js:14117:14)
```

## 期待する見せ方・挙動 / Expected behavior
- ワーニングが発生しないようにする

## 動作環境・ブラウザ / Environment
- Windows
- Chrome

**Comment by HyodaKazuaki** [comment]
参照
https://github.com/tokyo-metropolitan-gov/covid19/issues/2079

**Comment by HyodaKazuaki** [comment]
この件だけではないのですが、東京都のリポジトリでは改善がいくつか行われているのでできれば必要なコミットを東京都のリポジトリから持ってこられると嬉しいです
なにか方法はありますか？

**Comment by nomunomu0504** [comment]
東京のブランチからチェリーピックで持ってくるとか？

ブランチ切られてるなら、そのブランチをマージでもいいかと。

どうでしょう

**Comment by stshsn** [comment]
TimeBarChart.vue と TimeStackedBarChart.vue を修正したところワーニングは消えましたが、週別表示のグラフがおかしくなってしまいました。
![image](https://user-images.githubusercontent.com/34150349/78644124-5b737980-78f0-11ea-9433-e04df0f20d36.png)
![image](https://user-images.githubusercontent.com/34150349/78644323-aab9aa00-78f0-11ea-8569-c473c15a6d64.png)

**Comment by stshsn** [comment]
解決できたみたいなのでPRなげます。
