### ISSUE TITLE
docker-composeを用いた開発環境の用意に失敗する

### ISSUE THREAD

**Issue by HyodaKazuaki** [nomunomu0504/covid19#25]
## 起こっている問題 / The Problem
- `docker-compose up --build`を用いて開発環境を用意しようとするとエラーが発生する

## ログ / Log
```sh
covid19 % docker-compose up --build
Creating network "covid19_default" with the default driver
Building app
Step 1/9 : FROM node:10.19-alpine
 ---> 29fc59abc5de
Step 2/9 : ENV PROJECT_ROOTDIR /app/
 ---> Running in 0d6f9f41e555
Removing intermediate container 0d6f9f41e555
 ---> 641f6ae27d7c
Step 3/9 : WORKDIR $PROJECT_ROOTDIR
 ---> Running in dcf276e3bde3
Removing intermediate container dcf276e3bde3
 ---> c5339393ac55
Step 4/9 : COPY package.json yarn.lock $PROJECT_ROOTDIR
 ---> 3b1c0a403114
Step 5/9 : RUN yarn install
 ---> Running in 50eec6190ad0
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning sha.js@2.4.11: Invalid bin entry for "sha.js" (in "sha.js").
info fsevents@2.1.2: The platform "linux" is incompatible with this module.
info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.11: The platform "linux" is incompatible with this module.
info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "babel-jest > babel-preset-jest > @babel/plugin-syntax-object-rest-spread@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "vue-jest > @babel/plugin-transform-modules-commonjs@7.8.3" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "vue-property-decorator > vue-class-component@7.2.3" has unmet peer dependency "vue@^2.0.0".
warning "@nuxtjs/eslint-config-typescript > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning "@nuxtjs/stylelint-module > stylelint-webpack-plugin@1.2.3" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "@nuxtjs/vuetify > sass-loader@8.0.2" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
warning "@nuxtjs/vuetify > vuetify@2.2.15" has unmet peer dependency "vue@^2.6.4".
warning "@nuxtjs/vuetify > vuetify-loader@1.4.3" has unmet peer dependency "vue-template-compiler@^2.5.0".
warning "@nuxtjs/vuetify > vuetify-loader@1.4.3" has unmet peer dependency "webpack@^4.0.0".
warning " > @vue/test-utils@1.0.0-beta.31" has unmet peer dependency "vue@2.x".
warning " > @vue/test-utils@1.0.0-beta.31" has unmet peer dependency "vue-template-compiler@^2.x".
warning " > babel-jest@24.9.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "babel-jest > babel-preset-jest@24.9.0" has unmet peer dependency "@babel/core@^7.0.0".
warning "nuxt-purgecss > purgecss-webpack-plugin@1.6.0" has unmet peer dependency "webpack@^4 || ^3".
warning " > vue-jest@4.0.0-beta.2" has unmet peer dependency "@babel/core@7.x".
warning " > vue-jest@4.0.0-beta.2" has unmet peer dependency "vue@^2.x".
warning " > vue-jest@4.0.0-beta.2" has unmet peer dependency "vue-template-compiler@^2.x".
warning "vue-jest > ts-jest@23.10.5" has incorrect peer dependency "jest@>=22 <24".
[5/5] Building fresh packages...
Done in 72.10s.
Removing intermediate container 50eec6190ad0
 ---> f677cd15e318
Step 6/9 : COPY . $PROJECT_ROOTDIR
 ---> db8756fca512
Step 7/9 : EXPOSE 3000
 ---> Running in 8ecda83dbf9e
Removing intermediate container 8ecda83dbf9e
 ---> f697e85296e1
Step 8/9 : ENV HOST 0.0.0.0
 ---> Running in da9ca1bfc949
Removing intermediate container da9ca1bfc949
 ---> b9fb770d775b
Step 9/9 : CMD ["yarn", "dev"]
 ---> Running in bed95c4a657d
Removing intermediate container bed95c4a657d
 ---> e91463975bb8
Successfully built e91463975bb8
Successfully tagged covid19_app:latest
Creating covid19 ... done
Attaching to covid19
yarn run v1.21.1
$ cross-env NODE_OPTIONS=--max_old_space_size=2048 NODE_ENV=development nuxt-ts
covid19 | start Loading module
covid19 | ℹ PurgeCSS is not enabled because you are in dev mode
covid19 | 
covid19 |  FATAL  Cannot find module '@nuxtjs/sitemap'
covid19 | Require stack:
covid19 | - /app/node_modules/@nuxt/core/dist/core.js
covid19 | - /app/node_modules/@nuxt/cli/dist/cli-command.js
covid19 | - /app/node_modules/@nuxt/cli/dist/cli.js
covid19 | - /app/node_modules/@nuxt/typescript-runtime/bin/nuxt-ts.js
covid19 | 
covid19 |   Error: Cannot find module '@nuxtjs/sitemap'
covid19 |   Require stack:
covid19 |   - node_modules/@nuxt/core/dist/core.js
covid19 |   - node_modules/@nuxt/cli/dist/cli-command.js
covid19 |   - node_modules/@nuxt/cli/dist/cli.js
covid19 |   - node_modules/@nuxt/typescript-runtime/bin/nuxt-ts.js
covid19 |   at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:569:31)
covid19 |   at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:164:36)
covid19 |   at promise.then (node_modules/@nuxt/utils/dist/utils.js:1802:43)
covid19 | 
covid19 | 
covid19 |    ╭─────────────────────────────────────────────────────────────────╮
covid19 |    │                                                                 │
covid19 |    │   ✖ Nuxt Fatal Error                                            │
covid19 |    │                                                                 │
covid19 |    │   Error: Cannot find module '@nuxtjs/sitemap'                   │
covid19 |    │   Require stack:                                                │
covid19 |    │   - /app/node_modules/@nuxt/core/dist/core.js                   │
covid19 |    │   - /app/node_modules/@nuxt/cli/dist/cli-command.js             │
covid19 |    │   - /app/node_modules/@nuxt/cli/dist/cli.js                     │
covid19 |    │   - /app/node_modules/@nuxt/typescript-runtime/bin/nuxt-ts.js   │
covid19 |    │                                                                 │
covid19 |    ╰─────────────────────────────────────────────────────────────────╯
^[[24;80Rcovid19 | 
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
covid19 exited with code 1
```

## 期待する見せ方・挙動 / Expected Behavior
- コマンドを実行すると開発環境がビルドされ実行される

## 起こっている問題の再現手段 / Steps to Reproduce
1. docker及びdocker-composeをインストールしておく
2. このリポジトリをcloneする
3. cloneしたリポジトリ内で`docker-compose --build`を実行する

## 動作環境 / Environment
- macOS
- Docker version 19.03.8, build afacb8b
- docker-compose version 1.25.4, build 8d51620a

**Comment by HyodaKazuaki** [comment]
README.mdを読み込んでいませんでした
```sh
$ docker-compose run --rm app yarn install
```
を実行して解決しましたのでcloseします
